-- Create donations table for integrated donation gateway
create table if not exists public.donations (
    id bigint primary key generated by default as identity,
    user_id uuid references auth.users(id) on delete cascade,
    amount numeric not null,
    transaction_reference text unique not null,
    status text not null default 'pending', -- 'pending', 'successful', 'failed'
    payment_gateway text default 'scoa_pay',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.donations enable row level security;

-- Users can insert their own donations
create policy "Users can insert own donations"
    on public.donations for insert
    to authenticated
    with check (auth.uid() = user_id);

-- Users can view their own donations
create policy "Users can view own donations"
    on public.donations for select
    to authenticated
    using (auth.uid() = user_id);

-- Admins and finance can view all donations
create policy "Admins and finance can view all donations"
    on public.donations for select
    to authenticated
    using (
        exists (
            select 1 from public.profiles
            where profiles.id = auth.uid()
            and profiles.role in ('admin', 'super_admin', 'finance')
        )
    );

-- Admins and finance or system can update donations (e.g. status update)
create policy "Admins and finance can update donations"
    on public.donations for update
    to authenticated
    using (
        exists (
            select 1 from public.profiles
            where profiles.id = auth.uid()
            and profiles.role in ('admin', 'super_admin', 'finance')
        ) or auth.uid() = user_id
    );
