-- Create giving_settings table
create table if not exists public.giving_settings (
    id bigint primary key generated by default as identity,
    bank_name text not null default 'Equity Bank / Standard Bank',
    account_name text not null default 'Believers Fellowship Ministries',
    account_number text not null default '1002938472910',
    branch text not null default 'Main City Branch (Code: 045)',
    momo_name text not null default 'Believers Fellowship Tithes',
    momo_number text not null default '889922',
    airtel_name text not null default 'Believers Fellowship Offerings',
    airtel_number text not null default '554433',
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.giving_settings enable row level security;

-- Allow public/authenticated to read
create policy "Allow public read on giving_settings"
    on public.giving_settings for select
    using (true);

-- Allow admin and finance to update
create policy "Allow admin and finance to update giving_settings"
    on public.giving_settings for update
    using (
        exists (
            select 1 from public.profiles
            where profiles.id = auth.uid()
            and profiles.role in ('admin', 'super_admin', 'finance')
        )
    );

-- Allow admin to insert initial row if not exists
create policy "Allow admin to insert giving_settings"
    on public.giving_settings for insert
    with check (
        exists (
            select 1 from public.profiles
            where profiles.id = auth.uid()
            and profiles.role in ('admin', 'super_admin', 'finance')
        )
    );

-- Insert default row with id = 1
insert into public.giving_settings (id, bank_name, account_name, account_number, branch, momo_name, momo_number, airtel_name, airtel_number)
values (1, 'Equity Bank / Standard Bank', 'Believers Fellowship Ministries', '1002938472910', 'Main City Branch (Code: 045)', 'Believers Fellowship Tithes', '889922', 'Believers Fellowship Offerings', '554433')
on conflict (id) do nothing;
